### ISSUE TITLE
After opening the patch program, there is garbled text, and an error occurs after clicking the blue box

### ISSUE THREAD

**Issue by wangyuan0225** [teamxlpj/teamxlpj_resources#1]
### The problems you have encountered?

According to the solution, after clicking the program in “patch\dist\patch\patch.exe”, the interface text is garbled, and an error occurs after clicking the blue box.
![PixPin_2024-06-10_12-11-14](https://github.com/teamxlpj/teamxlpj_resources/assets/109222778/26e75195-8177-4e30-b3df-47fa372fd2d6)
According to the error message, I later tried to copy the “patch\dist\patch\_internal\InstallerMessage_RunlScript.ini” file to the “patch\dist\patch” directory. The interface text is garbled, but no error occurs after clicking the blue box, and there is no response. Sometimes the program may also become unresponsive after a while.
![PixPin_2024-06-10_12-19-21](https://github.com/teamxlpj/teamxlpj_resources/assets/109222778/d90b3cf2-4056-4c46-be4c-65dec0098e57)

**Comment by teamxlpj** [comment]
This is a known issue, caused by a coding error. We are currently reviewing the technical documentation to support utf-8. It is anticipated that this issue will be resolved after we have more members. We don't have plan to fix it now. It could be fixed after 1 or more versions.

**Comment by HyperTwo** [comment]
the same problem, then I changed the system language to English, it's still doesnt work

**Comment by teamxlpj** [comment]
> the same problem, then I changed the system language to English, it's still doesnt work

This is because we try to support chinese. But we met problems. We are now trying to find new members to solve this problem.

**Comment by lhfhybxm** [comment]
we have new patch now.

**Comment by wangyuan0225** [comment]
I didn't find the updated patch file on Github, can you tell me where to find it?

**Comment by Allenkore** [comment]
so  we will wait long time for this until you guys fix it
unless

**Comment by Allenkore** [comment]
does anyone  already started playing this game？I only saw some online water armies with on picture
