### ISSUE TITLE
A runtime issue with the new patch program

### ISSUE THREAD

**Issue by PhantomFL478** [teamxlpj/teamxlpj_resources#2]
### Before raising the issue...

- [X] I understand that Issues **must write in English** or it will not be viewed.
- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

When opening the new patch program, the loading process does not progress. I am sure that all wukong files are installed properly.
[Uploading patchcfg.loading…]()

### Version

patchv0.5.2

### Screenshots

![Uploading 屏幕截图 2024-06-11 110429.png…]()

**Comment by PhantomFL478** [comment]
<img width="862" alt="屏幕截图 2024-06-11 110429" src="https://github.com/teamxlpj/teamxlpj_resources/assets/172346477/e0d03057-f5a4-4b9c-b4f2-6aca97c33396">

**Comment by PhantomFL478** [comment]
[patchcfg.zip](https://github.com/user-attachments/files/15781712/patchcfg.zip)

**Comment by wangyuan0225** [comment]
You may need to wait a bit longer, I waited for about 5 minutes before the progress bar reached 1%.

**Comment by lhfhybxm** [comment]
it need time.

**Comment by Allenkore** [comment]
useless zip

**Comment by Allenkore** [comment]
i can see nothing    about  the progress bar

**Comment by Allenkore** [comment]
how can i open the file   i just unzip it  but i can’t use it

**Comment by Allenkore** [comment]
how can i open the file   i just unzip it  but i can’t use it

**Comment by Allenkore** [comment]
how can i open the file   i just unzip it  but i can’t use it
