### ISSUE TITLE
The patch crashes when it runs to over 70% but less than 80%.

### ISSUE THREAD

**Issue by wangyuan0225** [teamxlpj/teamxlpj_resources#3]
### Before raising the issue...

- [X] I understand that Issues **must write in English** or it will not be viewed.
- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

When running the latest patch, the window disappears when the patch runs more than 70%. That is, it crashes.

### Version

v0.5.2

### Screenshots

![PixPin_2024-06-11_15-32-10](https://github.com/teamxlpj/teamxlpj_resources/assets/109222778/cd60c581-ee5f-4606-a1d0-6e5063e52470)

### Anthing else?

[patchcfg.zip](https://github.com/user-attachments/files/15783992/patchcfg.zip)
The screenshot of the crash when running more than 70% was not captured. The screenshot above is a new attempt to run. There is no need to initialize when trying to run again.

**Comment by lhfhybxm** [comment]
did you notice the nct code?
if not appear, thats because the compress crc failed. your compress is broken. ask and check md5 who give you this compress.

**Comment by wangyuan0225** [comment]
The possible reason might indeed be that the compressed package is damaged, because when the patch program failed to run at the beginning, I directly used other compression software to decompress, and then the decompression failed, possibly causing the compressed package to be damaged at this time. The compressed package is downloaded from you guys. I will try again. If it still crashes, I will re-download "wukong".
