### ISSUE TITLE
Error in Win11 System

### ISSUE THREAD

**Issue by peterpuf** [teamxlpj/teamxlpj_resources#4]
### Before raising the issue...

- [X] I understand that Issues **must write in English** or it will not be viewed.
- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

When I try to use patch to decompress, it will execute normally and then prompt me to press enter to continue. When I press it, it will also prompt me that the wukong.zip-001 file does not exist, but it must exist

### Version

version: 0.5.2

**Comment by teamxlpj** [comment]
Through your describe, you didnot put patch and wukong in the same folder obviously. If you do so, please give more info like screenshots.
