### ISSUE TITLE
77% and then report an error

### ISSUE THREAD

**Issue by LS-Cloud966** [teamxlpj/teamxlpj_resources#7]
### Before raising the issue...

- [X] I understand that Issues **must write in English** or it will not be viewed.
- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

I want to know if this error is caused by a corrupted file in the 137th compressed file

### Version

the pach file used is the latest

### Screenshots

![image](https://github.com/teamxlpj/teamxlpj_resources/assets/172944665/1189a22b-30d8-461d-bb96-b6690a1e5336)

**Comment by teamxlpj** [comment]
compressed crc check failed. your comperssed has been damaged.
