### ISSUE TITLE
An unexpected failed error occurred when the patch runs to 77%.

### ISSUE THREAD

**Issue by wangyuan0225** [teamxlpj/teamxlpj_resources#9]
### Before raising the issue...

- [X] I understand that Issues **must write in English** or it will not be viewed.
- [X] I understand that Issues are for feedback and problem solving, not trolling the comments section, and will provide as much information as possible to help solve the problem.
- [X] I filled in a short, clear title so that developers could quickly identify the general problem when going through the issue list. Instead of "Some suggestions", "Stuck", etc.
- [X] I have checked the latest beta update and there is no mention of the bug being fixed.
- [X] I have reviewed the pinned issues and confirmed that my issue is not mentioned.

### Description

When running the latest patch, an unexpected failed error occurred when the patch runs to 77%.

### Version

v0.5.3

### Screenshots

![PixPin_2024-06-18_21-00-14](https://github.com/teamxlpj/teamxlpj_resources/assets/109222778/b4f9da2b-a9d9-47e0-85a0-958f31f44aae)

### Anthing else?

[patchcfg.zip](https://github.com/user-attachments/files/15887007/patchcfg.zip)

**Comment by wangyuan0225** [comment]
I have re-downloaded 137 compressed files of Wukong. I confirm that there were no illegal operations after downloading, and I directly used the 0.5.3 version of the patch to unzip, but it still failed to unzip. Can you provide a Wukong compressed file that does not need to be unzipped with a patch? I have failed several times already.

**Comment by teamxlpj** [comment]
To avoid legal issues, we cant provide. Maybe u can find other resources on russians website if you still cant open our compressed. We might not fix in the future cause we can't reproduce this problem and it seems rarely occur in our records. Whatever, thanks for ur support.
